### ISSUE TITLE
can it be useful on other brand like redmi, vivo, etc..

### ISSUE THREAD

**Issue by nonconformistqi** [B83C/huawei_bootloader_unlocker#1]
can it be useful on other brand like redmi, vivo, etc..

**Comment by B83C** [comment]
oh well, I can tell its the most ridiculous approach to unlocking bootloaders. And should you want to try, I would recommend that you look for other methods. Having run this on my pc, I found out that it would take more than a century to unlock my bootloader, and considering how slow the adb interface is (around 222ms per request), this method would simply be inefficient. In hindsight, I would suggest that you get a new phone with official bootloader unlocking available. And Redmi does have the service whereas vivo is impossible ( you may verify it here : [.](https://www.vivo.com/en/support/questionList?categoryId=10045) )

**Comment by B83C** [comment]
I am sorry if I have disappointed you. :(

**Comment by nonconformistqi** [comment]
thanks, @B83C
